RealityETH/subjectivocracy

contracts/RealityToken.sol
These functions are needed to make advanced withdraw requests from a smart contract holding realityTokens. As example see here:https://github.com/josojo/GnosisMarketsANDrealitycoins
=> addition of  reading functions in RealityToken.sol

.gitmodules, development/contracts/ForkableGlobalExitRoot.sol, development/contracts/ForkonomicToken.sol, development/contracts/interfaces/IForkableGlobalExitRoot.sol, development/contracts/interfaces/IForkonomicToken.sol, development/contracts/mixin/ForkableStructure.sol, remappings.txt, test/ForkableGlobalExitRoot.t.sol, test/ForkableUUPS.t.sol, test/ForkonomicToken.t.sol
adding implementation and test of forkonomic token
=> Forkonomic token

.gitignore, development/README.md, development/contracts/Auction_ERC20.sol
Replaces:
https://github.com/RealityET
all comments from the PR should be addressed
since this is anyways just a draft contract that is not properly tested, I think we can just merge the renaming work. Getting things done properly in another PR will be done later
=> Small fixes in auction contract

development/contracts/lib/CreateChildren.sol, test/ForkableBridge.t.sol, test/ForkableGlobalExitRoot.t.sol, test/ForkableStructure.t.sol, test/ForkableZkEVM.t.sol, test/ForkingManager.t.sol, test/ForkonomicToken.t.sol
I am using the transparent upgradeable proxy, as this is the best fit:
- best good practice,
- mostly used both other projects
- and used by polygon code itself.
=> Using an actual upgradeable proxy

development/contracts/ForkingManager.sol, test/ForkingManager.t.sol
=> correct initialisation of bridge

contracts/ForkingManager.sol, test/ForkingManager.t.sol, test/L1GlobalChainInfoPublisher.t.sol, test/L1GlobalForkRequester.t.sol
We want to deploy the forking manager as proxy. Hence its important to not do any storage operation during deployment.
=> make forking manager compatible with proxy infra

package.json, src/scripts/depositForkonomicTokenIntoBridge.js
PR already approved in the other PR. Redid the PR to avoid merge conflicts
=> update deposit script

contracts/ForkingManager.sol, contracts/interfaces/IForkingManager.sol, test/ForkingManager.t.sol, test/L1GlobalChainInfoPublisher.t.sol, test/L1GlobalForkRequester.t.sol
I am making it configurable, such that we can test it easier in sepolia as well.
=> make fork preparation time configurable

hardhat.config.js
Sorry, I screwed this up while rebasing when I merged the deployment scripts
=> Put the zkEVMServices config in the right place

test/ForkableBridge.t.sol
Only renaming of public variable
=> Linting fix

contracts/L1GlobalChainInfoPublisher.sol, contracts/L1GlobalForkRequester.sol, contracts/L2ChainInfo.sol, contracts/L2ForkArbitrator.sol, test/L1GlobalChainInfoPublisher.t.sol, test/L2ChainInfo.t.sol
work in progress, but already good to merge
- introducing more test
- cleaning out some todos,
-simple refactors
- errors instead of require satements
=> Refactor of periphery contracts

.solhint.json, .solhintignore, contracts/AdjudicationFramework.sol, contracts/ChainIdManager.sol, contracts/ForkableBridge.sol, contracts/ForkableGlobalExitRoot.sol, contracts/ForkableZkEVM.sol, contracts/ForkingManager.sol, contracts/L1GlobalForkRequester.sol, contracts/interfaces/IForkableBridge.sol, test/AdjudicationIntegration.t.sol, test/ChainIdManager.t.sol, test/ForkableBridge.t.sol, test/ForkableZkEVM.t.sol, test/ForkingManager.t.sol, test/ForkonomicToken.t.sol, test/L1GlobalChainInfoPublisher.t.sol, test/L1GlobalForkRequester.t.sol, test/MoneyBox.t.sol, test/testcontract/ForkableBridgeWrapper.sol, test/testcontract/ForkableExitMock.sol, test/testcontract/ForkableZkEVMMock.sol, test/testcontract/MockPolygonZkEVMBridge.sol
Replaces: #177, since this was build on top of other adjudication framework PR.
=> Fix lintings

contracts/ForkonomicToken.sol
I don't know why I implemented this funciton. But I think I never really intended to use it, since it is also not tested, nor in the interface contract.
=> Removing unnecessary function in forkonomicToken

.gitignore, README.md
Tooling to overview our coverage:
=> coverage tooling

.solhint.json, contracts/ForkableBridge.sol, contracts/ForkonomicToken.sol, contracts/lib/BridgeAssetOperations.sol, contracts/lib/CreateChildren.sol, contracts/mixin/ForkableStructure.sol, test/CreateChildren.t.sol, test/ForkableStructure.t.sol, test/ForkingManager.t.sol, test/ForkonomicToken.t.sol, test/L1GlobalChainInfoPublisher.t.sol, test/testcontract/CreateChildrenWrapper.sol, test/testcontract/ForkableStructureWrapper.sol, test/utils/Util.sol
Result of a contract review:
Many small modifications, mostly wording in comments
additions of tests
=> Additions of tests and spelling corrects

test/ForkableBridge.t.sol, test/ForkingManager.t.sol
1 test improvement and one additional test
=> Test improvements

package-lock.json, package.json
closes https://github.com/RealityETH/subjectivocracy/issues/101
=> solhint update + prettier update

.github/workflows/testhardhat.yml, package-lock.json, package.json
We had several npm packages with critical error. So I ran npm audit fix --force.
=> updating with npm audit fix --force

src/deployment/3_deployContracts.js
forkingManager was not defined
=> Fix deployment script

contracts/L2ForkArbitrator.sol, contracts/interfaces/IL2ForkArbitrator.sol, test/L2ForkArbitrator.t.sol
replaces: https://github.com/RealityETH/subjectivocracy/pull/214
=> Allow cancellation of L2 ForkArbitrator requests

src/deployment/verifyContracts.js
Improving the verify script to also verify the implemenations
=> improve verify script

src/scripts/compareZkevmStateToChild.js
Script that compares data between different deployments. Helps for debugging, though not very important.
=> debugging script

src/common/common.js
In case one has several in flight transactions, this function was quite helpful.. I am commiting it here, since I had this issue several times now
=> adding option for nonce config

docs/deploy_parameters.txt, src/deployment/README.md
=> Document a keyless deployment edge case, add some detail about the
