RealityETH/subjectivocracy

development/contracts/mixin/ForkableUUPS.sol
remappings.txt
test/ForkableUUPS.t.sol
test/testcontract/ForkableUUPSWrapper.sol
test/utils/Util.sol
test/utils/utils.sol

The new contract implements the UUPS pattern and can later be inherited by all contracts that we require updatable.

Forkable uups

---

.solhint.json
development/contracts/ForkableZkEVM.sol
development/contracts/WhitelistArbitrator.sol
development/contracts/interfaces/IForkableZkEVM.sol
test/ForkableZkEVM.t.sol

Forkable zkevm implementation.
The only tricky thing was how to deal with the state updates.
There are 4 state updates(https://zkevm.polygon.technology/docs/protocol/state-management)
sequencer confirmation(for us unimportant)
sequenced(after the sequencer submitted payload to L1). We will not consider this for the forking process
verified(after a zk proof has been submitted)
consolidated(after a period called pendingStateTimeout - if the proof was given by someone random - or after verified by the trusted sequencer).
I decided that I want to only post consolidated stateRoots into the new forks. This gives the guarantees similar to the original implementation, but it might be that the verified state is not considered, in a forking situations, if it is not yet consolidated.
This might not …

zkevm prototype

---

contracts/interfaces/IForkableStructure.sol
contracts/mixin/ForkableStructure.sol

Immediate motivation is to be able to look up the `forkmanager()` of a bridge to route the fork requests to it, but it seems like these should be exposed in the interface anyhow as they're present when you inherit `ForkableStructure`.
Arguably `forkmanager` should be renamed but if we do that we'll do it in another commit.

Expose the forkmanager() and parentContract() methods in the interface

---

contracts/ForkingManager.sol
contracts/interfaces/IForkingManager.sol
test/ForkingManager.t.sol

This PR allows to submit delayed/scheduled fork proposals.
I image that each adjudication framework will enforce its own delay and hence, we don't enforce a specific number.
The main concern about this implementation is that different delays might cause overlapping scheduled forks. This implementation copies the forkschedules then just to the new forking managers. This is okay, as different forks should be scheduled to remove different courts.(This could be enforced by outside non-core helper contracts at the submission time of the tx.

Delayed fork proposals

---

contracts/ChainIdManager.sol
test/ChainIdManager.t.sol
test/ForkingManager.t.sol

Rewriting the chainId manger using the idea to introduce a cost to use up a chainID.
ChainIds are given out sequentially, but an owner can denylist certain chainId that are used by other projects, such that these chainIds are not handed out by the chainIdManager

rewrite chainIdManager

---

contracts/AdjudicationFramework.sol
contracts/ChainIdManager.sol
contracts/ForkingManager.sol
contracts/L1GlobalChainInfoPublisher.sol
contracts/L1GlobalForkRequester.sol
contracts/L2ChainInfo.sol
contracts/L2ForkArbitrator.sol
contracts/interfaces/IForkingManager.sol
contracts/interfaces/IRealityETH.sol
contracts/lib/CalculateMoneyBoxAddress.sol
contracts/lib/CreateChildren.sol
contracts/lib/reality-eth/RealityETH-3.0.sol
contracts/mixin/MoneyBox.sol
test/AdjudicationIntegration.t.sol
test/ChainIdManager.t.sol
test/ForkingManager.t.sol
test/L1GlobalChainInfoPublisher.t.sol
test/L1GlobalForkRequester.t.sol
test/MoneyBox.t.sol
test/RealityETH.t.sol
test/testcontract/ExampleMoneyBoxUser.sol
test/testcontract/ExampleToken.sol
test/testcontract/MockPolygonZkEVMBridge.sol

just running yarn fmt...
I really thought we would have a test in CI ... but somehow we did not..

formatting of previous PR

---

contracts/ForkingManager.sol
test/ForkingManager.t.sol
test/L1GlobalChainInfoPublisher.t.sol
test/L1GlobalForkRequester.t.sol

the _setImplementation of the proxy would revert, if the address are not contracts. we need to avoid that
Covers parts of #103 
See here: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v4.9.5/contracts/proxy/ERC1967/ERC1967Upgrade.sol#L40

do not allow non-contract address as new implementations

---

contracts/ForkingManager.sol
test/ForkingManager.t.sol

It's better if we know the chainId already before, and not just in the moment of the creation of the forks

Reserve chainId already during initiation of fork

---

contracts/ForkableGlobalExitRoot.sol
contracts/ForkingManager.sol
contracts/interfaces/IForkableGlobalExitRoot.sol
test/ForkableGlobalExitRoot.t.sol
test/ForkingManager.t.sol
test/L1GlobalChainInfoPublisher.t.sol
test/L1GlobalForkRequester.t.sol

Sets global exit root duing forking process

---

contracts/ForkableBridge.sol
contracts/ForkableGlobalExitRoot.sol
contracts/ForkableZkEVM.sol
contracts/ForkingManager.sol
contracts/ForkonomicToken.sol
contracts/L1GlobalForkRequester.sol
contracts/interfaces/IForkableBridge.sol
contracts/interfaces/IForkableGlobalExitRoot.sol
contracts/interfaces/IForkableZkEVM.sol
contracts/interfaces/IForkingManager.sol
contracts/interfaces/IForkonomicToken.sol
contracts/lib/CreateChildren.sol
contracts/mixin/ForkableStructure.sol
test/ForkableBridge.t.sol
test/ForkableGlobalExitRoot.t.sol
test/ForkableStructure.t.sol
test/ForkableZkEVM.t.sol
test/ForkingManager.t.sol
test/ForkonomicToken.t.sol
test/L1GlobalChainInfoPublisher.t.sol
test/L1GlobalForkRequester.t.sol
test/testcontract/ForkableStructureWrapper.sol

No longer allow for new implementation during forking. These will be introduced by the security concil only if the community agrees. If there is a conflict on whether upgrades should be introduced, the chain can first split into two and then the council can do the upgrade on one chain only.
I really like this PR, since it makes our code simpler.
closes #136 
closes #76

No upgrades via forks

---

contracts/ForkableBridge.sol
contracts/interfaces/IForkableBridge.sol
contracts/interfaces/IForkableStructure.sol
contracts/mixin/ForkableStructure.sol
test/ForkableBridge.t.sol
test/ForkableGlobalExitRoot.t.sol
test/ForkableZkEVM.t.sol
test/ForkingManager.t.sol
test/L1GlobalChainInfoPublisher.t.sol

This indeed influences the contract size:
In this branch:
| Contract                    | Size (kB)
| ForkableBridge              | 24.137
In main branch:
| Contract                    | Size (kB)
| ForkableBridge              | 24.435
If you approve these changes, I will do the rest in another PR.

First round of revert string removals

---

contracts/ForkingManager.sol
contracts/L1GlobalForkRequester.sol
contracts/interfaces/IForkingManager.sol
test/ForkingManager.t.sol
test/L1GlobalForkRequester.t.sol

Remove the function can fork, as it coincides with existing functions in the current implementation. If it later no longer coincides, we can readded it.

remove can fork

---

contracts/ForkableBridge.sol
contracts/interfaces/IForkableBridge.sol
test/ForkableBridge.t.sol

closes #144
(wrapped tokens from L2 need to be send burn and send to the children bridges by their users).
(gasToken can be burned all at once with the current implementation and send to one child in one transaction + to the other child in a second transaction).
(L1 tokens - hard assets -  will be send to the child contract via the call from the hardasset manager.)

Do not allow gasTokens to be managed by hard asset manager

---

contracts/L2ForkArbitrator.sol

In the bridging contract we have:
if (msg.value != amount) {
revert AmountDoesNotMatchMsgValue();
}
Hence, the interface to bridge was called correctly.

fix bridging todo

---

foundry.toml
hardhat.config.js

With the current contract size, we can increase the runs close to 500 before breaking the code limit for the forkable bridge contract.
Code limit can be checked by forge build --sizes.

optimize the number of optimizer runs

---

.github/workflows/test.yml
test/ForkableBridge.t.sol

We merged the following warning:
```
Warning (2519): This declaration shadows an existing declaration.
--> test/ForkableBridge.t.sol:93:9:
|
93 |         address forkmanager = forkableBridge.forkmanager();
|         ^^^^^^^^^^^^^^^^^^^
Note: The shadowed declaration is here:
--> test/ForkableBridge.t.sol:22:5:
|
22 |     address public forkmanager = address(0x123);
```

Make tests fail on compilation warnings

---

contracts/L1GlobalForkRequester.sol
contracts/L2ForkArbitrator.sol
test/AdjudicationIntegration.t.sol

This PR gives the arbitration payer full control over proceedings of their arbitration in the L2ForkArbitrator.
In the L1ForkRequester, the a failed requests always has to be returned to the payee and it needs to be restarted on the L2. There are also no longer options for topups, but I think this is also not needed, as the L2ForkRequestor always checks for the correct arbitrationfee amount.
Also this PR prevents a gasAuction in the L2ForkArbtirator by giving only the payee the power to either cancel or submit their forkrequest. 
closes: #170

Arbitration proceedings control management

---

.github/workflows/testhardhat.yml

Disabling is done, since a dependency issue is prevailing.
Locally, the tests are working well.

Temporarly disable hardhat test in CI

---

.github/workflows/test.yml
.gitmodules
remappings.txt

This removes the need to have duplicate settings in package.json (for hardhat) and .gitmodules / remappings.txt (for forge) by making forge use the hardhat method. It also lets us use git submodules less which is good because they tend to confuse the hell out of everyone.

Remove submodules except for the forge standard libraries and rely on npm

---

contracts/lib/BridgeAssetOperations.sol

better metadata reading to tokens from being stuck in the bridge
